"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import Link from "next/link";
import OrdersManager from "./OrdersManager";
import InventoryManager from "./InventoryManager";
import DashboardPanel from "./DashboardPanel";
import {
  AdminLang,
  CATEGORIES,
  STONE_TYPES,
  METAL_TYPES,
  STOCK_STATUSES,
  CATEGORY_LABELS,
  STONE_LABELS,
  METAL_LABELS,
  STOCK_LABELS,
  totalCost,
  marginPct,
  fmtUSD,
} from "@/lib/admin-constants";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DbProduct = Record<string, any>;

const IMAGE_FIELDS = ["image_main", "image2", "image3", "image4"] as const;
type ImageField = typeof IMAGE_FIELDS[number];

type Tab = "dashboard" | "products" | "inventory" | "orders";

const t = {
  en: {
    adminLogin: "Admin Login",
    password: "Admin password",
    invalidPassword: "Invalid password",
    login: "Login",
    title: "Ambar & Larimar Admin",
    viewSite: "View Site",
    logout: "Logout",
    dashboard: "Dashboard",
    products: "Products",
    inventory: "Inventory",
    orders: "Orders",
    productsInDb: "products in database",
    initDb: "Initialize Database",
    addProduct: "+ Add Product",
    loading: "Loading products...",
    dbNotConnected: "Database Not Connected",
    dbNotConnectedMsg: "Click the button below to create the products table in your database.",
    noProducts: "No Products Yet",
    noProductsMsg: 'Click "Add Product" to create your first product.',
    addProductTitle: "Add Product",
    editProduct: "Edit",
    cancel: "Cancel",
    name: "Name",
    slug: "Slug",
    sku: "SKU",
    skuHint: "Auto-generated from stone/metal/category",
    regenerateSku: "Regenerate",
    retailPrice: "Retail Price",
    wholesalePrice: "Wholesale Price",
    category: "Category",
    stoneType: "Stone Type",
    metalType: "Metal Type",
    stockStatus: "Stock Status",
    stockQty: "Stock Qty",
    weight: "Weight (grams)",
    dimensions: "Dimensions",
    stoneOrigin: "Stone Origin",
    sortOrder: "Sort Order",
    minWholesaleQty: "Min Wholesale Qty",
    descriptions: "Descriptions",
    generateAi: "Generate with AI",
    generating: "Generating...",
    shortDesc: "Short Description",
    fullDesc: "Full Description",
    featured: "Featured",
    wholesaleEligible: "Wholesale Eligible",
    newArrival: "New Arrival",
    visible: "Visible",
    images: "Images",
    mainPhoto: "Main photo (thumbnail)",
    uploadPhotos: "Upload photos",
    uploading: "Uploading...",
    dropHere: "or drop images here",
    setAsMain: "Set as main",
    mainBadge: "Main",
    pasteUrl: "Or paste URL",
    createProduct: "Create Product",
    saveChanges: "Save Changes",
    autoGenerated: "auto-generated from name",
    image: "Image",
    price: "Price",
    stock: "Stock",
    status: "Status",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this product?",
    hidden: "Hidden",
    productCreated: "Product created!",
    productUpdated: "Product updated!",
    productDeleted: "Product deleted",
    saveFailed: "Failed to save product",
    dbInitialized: "Database initialized!",
    dbInitFailed: "Failed to initialize database. Check DATABASE_URL env var.",
    uploadFailed: "Upload failed",
    enterNameFirst: "Enter a product name first",
    descriptionsGenerated: "Descriptions generated!",
    generateFailed: "Failed to generate descriptions",
    costs: "Costs & Margin",
    materialCost: "Material",
    laborCost: "Labor",
    packagingCost: "Packaging",
    shippingCostField: "Shipping",
    totalCost: "Total Cost",
    margin: "Margin",
  },
  es: {
    adminLogin: "Inicio de Sesion Admin",
    password: "Contrasena de admin",
    invalidPassword: "Contrasena invalida",
    login: "Entrar",
    title: "Ambar & Larimar Admin",
    viewSite: "Ver Sitio",
    logout: "Salir",
    dashboard: "Panel",
    products: "Productos",
    inventory: "Inventario",
    orders: "Pedidos",
    productsInDb: "productos en la base de datos",
    initDb: "Inicializar Base de Datos",
    addProduct: "+ Agregar Producto",
    loading: "Cargando productos...",
    dbNotConnected: "Base de Datos No Conectada",
    dbNotConnectedMsg: "Haz clic en el boton de abajo para crear la tabla de productos en tu base de datos.",
    noProducts: "Sin Productos",
    noProductsMsg: 'Haz clic en "Agregar Producto" para crear tu primer producto.',
    addProductTitle: "Agregar Producto",
    editProduct: "Editar",
    cancel: "Cancelar",
    name: "Nombre",
    slug: "Slug",
    sku: "SKU",
    skuHint: "Auto-generado (piedra/metal/categoria)",
    regenerateSku: "Regenerar",
    retailPrice: "Precio Retail",
    wholesalePrice: "Precio Mayoreo",
    category: "Categoria",
    stoneType: "Tipo de Piedra",
    metalType: "Tipo de Metal",
    stockStatus: "Estado de Stock",
    stockQty: "Cant. en Stock",
    weight: "Peso (gramos)",
    dimensions: "Dimensiones",
    stoneOrigin: "Origen de la Piedra",
    sortOrder: "Orden",
    minWholesaleQty: "Min Cant. Mayoreo",
    descriptions: "Descripciones",
    generateAi: "Generar con IA",
    generating: "Generando...",
    shortDesc: "Descripcion Corta",
    fullDesc: "Descripcion Completa",
    featured: "Destacado",
    wholesaleEligible: "Apto para Mayoreo",
    newArrival: "Nuevo",
    visible: "Visible",
    images: "Imagenes",
    mainPhoto: "Foto principal (miniatura)",
    uploadPhotos: "Subir fotos",
    uploading: "Subiendo...",
    dropHere: "o arrastra imagenes aqui",
    setAsMain: "Usar como principal",
    mainBadge: "Principal",
    pasteUrl: "O pegar URL",
    createProduct: "Crear Producto",
    saveChanges: "Guardar Cambios",
    autoGenerated: "auto-generado del nombre",
    image: "Imagen",
    price: "Precio",
    stock: "Stock",
    status: "Estado",
    actions: "Acciones",
    edit: "Editar",
    delete: "Eliminar",
    deleteConfirm: "Eliminar este producto?",
    hidden: "Oculto",
    productCreated: "Producto creado!",
    productUpdated: "Producto actualizado!",
    productDeleted: "Producto eliminado",
    saveFailed: "Error al guardar producto",
    dbInitialized: "Base de datos inicializada!",
    dbInitFailed: "Error al inicializar. Verifica la variable DATABASE_URL.",
    uploadFailed: "Error al subir",
    enterNameFirst: "Ingresa un nombre primero",
    descriptionsGenerated: "Descripciones generadas!",
    generateFailed: "Error al generar descripciones",
    costs: "Costos y Margen",
    materialCost: "Material",
    laborCost: "Mano de Obra",
    packagingCost: "Empaque",
    shippingCostField: "Envio",
    totalCost: "Costo Total",
    margin: "Margen",
  },
};

const EMPTY_PRODUCT: DbProduct = {
  name: "", slug: "", sku: "",
  description: "", short_description: "",
  description_es: "", short_description_es: "",
  description_de: "", short_description_de: "",
  price_retail: 0, price_wholesale: 0, min_wholesale_qty: 1,
  material_cost: 0, labor_cost: 0, packaging_cost: 0, shipping_cost: 0,
  stock_quantity: 0,
  category: "pendants", stone_type: "larimar", metal_type: "sterling-silver",
  image_main: "", image2: "", image3: "", image4: "",
  stock_status: "in-stock", featured: false, wholesale_eligible: true, new_arrival: false,
  weight_grams: 0, dimensions: "", stone_origin: "Dominican Republic",
  visible: true, sort_order: 999,
};

export default function AdminDashboard() {
  const [lang, setLang] = useState<AdminLang>("en");
  const [authed, setAuthed] = useState(false);
  const [password, setPassword] = useState("");
  const [loginError, setLoginError] = useState("");
  const [products, setProducts] = useState<DbProduct[]>([]);
  const [loading, setLoading] = useState(false);
  const [editing, setEditing] = useState<DbProduct | null>(null);
  const [isNew, setIsNew] = useState(false);
  const [uploadingField, setUploadingField] = useState<string | null>(null);
  const [dragActive, setDragActive] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [regenSkuLoading, setRegenSkuLoading] = useState(false);
  const [dbReady, setDbReady] = useState(true);
  const [message, setMessage] = useState("");
  const [activeTab, setActiveTab] = useState<Tab>("dashboard");

  const l = t[lang];

  useEffect(() => {
    const saved = localStorage.getItem("admin_lang") as AdminLang | null;
    if (saved === "en" || saved === "es") setLang(saved);
  }, []);

  function toggleLang() {
    const next = lang === "en" ? "es" : "en";
    setLang(next);
    localStorage.setItem("admin_lang", next);
  }

  const fetchProducts = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/admin/products");
      if (res.status === 401) { setAuthed(false); return; }
      if (res.ok) {
        const data = await res.json();
        setProducts(data);
        setDbReady(true);
      } else {
        setDbReady(false);
      }
    } catch {
      setDbReady(false);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    if (authed) fetchProducts();
  }, [authed, fetchProducts]);

  // Scroll to top whenever the edit modal opens or closes
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [editing]);

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault();
    setLoginError("");
    const res = await fetch("/api/admin/auth", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ password }),
    });
    if (res.ok) {
      setAuthed(true);
      setPassword("");
    } else {
      setLoginError(l.invalidPassword);
    }
  }

  async function handleLogout() {
    await fetch("/api/admin/auth", { method: "DELETE" });
    setAuthed(false);
    setProducts([]);
  }

  async function handleSetupDb() {
    const res = await fetch("/api/admin/setup", { method: "POST" });
    if (res.ok) {
      setMessage(l.dbInitialized);
      setDbReady(true);
      fetchProducts();
    } else {
      setMessage(l.dbInitFailed);
    }
    setTimeout(() => setMessage(""), 5000);
  }

  async function handleSave() {
    if (!editing) return;
    const slug = editing.slug || editing.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    const payload = { ...editing, slug };

    let res;
    if (isNew) {
      res = await fetch("/api/admin/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
    } else {
      res = await fetch(`/api/admin/products/${editing.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
    }

    if (res.ok) {
      setEditing(null);
      setIsNew(false);
      setMessage(isNew ? l.productCreated : l.productUpdated);
      fetchProducts();
    } else {
      setMessage(l.saveFailed);
    }
    setTimeout(() => setMessage(""), 3000);
  }

  async function handleDelete(id: string) {
    if (!confirm(l.deleteConfirm)) return;
    const res = await fetch(`/api/admin/products/${id}`, { method: "DELETE" });
    if (res.ok) {
      setMessage(l.productDeleted);
      fetchProducts();
    }
    setTimeout(() => setMessage(""), 3000);
  }

  async function uploadOne(field: string, file: File): Promise<string | null> {
    setUploadingField(field);
    const formData = new FormData();
    formData.append("file", file);
    try {
      const res = await fetch("/api/admin/upload", { method: "POST", body: formData });
      const data = await res.json().catch(() => null);
      if (res.ok && data?.url) {
        return data.url as string;
      }
      const errMsg = data?.error || `HTTP ${res.status}`;
      setMessage(`${l.uploadFailed}: ${errMsg}`);
      return null;
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : "network error";
      setMessage(`${l.uploadFailed}: ${errMsg}`);
      return null;
    } finally {
      setUploadingField(null);
    }
  }

  async function handleFilesSelected(files: FileList | File[]) {
    if (!editing) return;
    const arr = Array.from(files).filter((f) => f.type.startsWith("image/"));
    if (arr.length === 0) return;

    // Find empty slots in order
    const emptySlots: ImageField[] = IMAGE_FIELDS.filter((f) => !editing[f]) as ImageField[];
    const toProcess = arr.slice(0, emptySlots.length);

    for (let i = 0; i < toProcess.length; i++) {
      const slot = emptySlots[i];
      const file = toProcess[i];
      setMessage(`Uploading ${file.name}... (${i + 1}/${toProcess.length})`);
      const url = await uploadOne(slot, file);
      if (url) {
        setEditing((prev) => prev ? { ...prev, [slot]: url } : prev);
      }
    }
    setMessage(`Uploaded ${toProcess.length} image${toProcess.length > 1 ? "s" : ""}`);
    setTimeout(() => setMessage(""), 2500);
  }

  function openPicker() {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/*";
    input.multiple = true;
    input.onchange = (e) => {
      const files = (e.target as HTMLInputElement).files;
      if (files) handleFilesSelected(files);
    };
    input.click();
  }

  function setAsMain(field: ImageField) {
    if (!editing || field === "image_main" || !editing[field]) return;
    const currentMain = editing.image_main;
    setEditing({ ...editing, image_main: editing[field], [field]: currentMain });
  }

  function clearImage(field: ImageField) {
    if (!editing) return;
    setEditing({ ...editing, [field]: "" });
  }

  async function handleRegenerateSku() {
    if (!editing) return;
    setRegenSkuLoading(true);
    try {
      const res = await fetch("/api/admin/sku/preview", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          stone_type: editing.stone_type,
          metal_type: editing.metal_type,
          category: editing.category,
        }),
      });
      if (res.ok) {
        const { sku } = await res.json();
        setEditing({ ...editing, sku });
      }
    } finally {
      setRegenSkuLoading(false);
    }
  }

  async function handleGenerateDescriptions() {
    if (!editing?.name) {
      setMessage(l.enterNameFirst);
      setTimeout(() => setMessage(""), 3000);
      return;
    }
    setGenerating(true);
    try {
      const res = await fetch("/api/admin/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: editing.name,
          category: editing.category,
          stoneType: editing.stone_type,
          metalType: editing.metal_type,
          stoneOrigin: editing.stone_origin,
          weightGrams: editing.weight_grams,
          dimensions: editing.dimensions,
        }),
      });
      if (res.ok) {
        const { en, es, de } = await res.json();
        setEditing((prev) => prev ? {
          ...prev,
          short_description: en.short,
          description: en.full,
          short_description_es: es.short,
          description_es: es.full,
          short_description_de: de.short,
          description_de: de.full,
        } : prev);
        setMessage(l.descriptionsGenerated);
      } else {
        const err = await res.json();
        setMessage(err.error || l.generateFailed);
      }
    } catch {
      setMessage(l.generateFailed);
    }
    setGenerating(false);
    setTimeout(() => setMessage(""), 3000);
  }

  const editingMargin = useMemo(() => {
    if (!editing) return { cost: 0, margin: 0 };
    const cost = totalCost(editing);
    const m = marginPct(Number(editing.price_retail || 0), cost);
    return { cost, margin: m };
  }, [editing]);

  const LangToggle = () => (
    <button onClick={toggleLang}
      className="px-2.5 py-1 rounded font-ui text-xs font-medium border border-cream/20 hover:bg-cream/10 transition-colors text-cream">
      {lang === "en" ? "ES" : "EN"}
    </button>
  );

  // --- Login Screen ---
  if (!authed) {
    return (
      <div className="min-h-screen bg-navy flex items-center justify-center px-4 relative">
        <div className="absolute top-4 right-4">
          <button onClick={toggleLang}
            className="px-3 py-1.5 rounded font-ui text-xs font-medium border border-cream/20 hover:bg-cream/10 transition-colors text-cream">
            {lang === "en" ? "Espanol" : "English"}
          </button>
        </div>
        <div className="bg-white rounded-lg p-8 w-full max-w-sm shadow-xl">
          <h1 className="font-heading text-2xl tracking-[0.1em] text-ocean text-center mb-6">
            {l.adminLogin}
          </h1>
          <form onSubmit={handleLogin} className="space-y-4">
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder={l.password}
              className="w-full border border-gold/20 px-4 py-3 rounded font-ui text-sm focus:outline-none focus:border-gold"
              autoFocus
            />
            {loginError && <p className="text-red-600 font-ui text-sm">{loginError}</p>}
            <button
              type="submit"
              className="w-full bg-ambar-light hover:bg-ambar text-navy py-3 rounded font-ui text-sm tracking-wider uppercase font-medium"
            >
              {l.login}
            </button>
          </form>
        </div>
      </div>
    );
  }

  // --- Edit/New Modal ---
  if (editing) {
    const mainImg = editing.image_main;

    return (
      <div className="min-h-screen bg-cream-dark p-4 sm:p-8">
        <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm p-6 sm:p-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="font-heading text-xl tracking-[0.08em] text-ocean">
              {isNew ? l.addProductTitle : `${l.editProduct}: ${editing.name}`}
            </h2>
            <button onClick={() => { setEditing(null); setIsNew(false); }} className="text-ocean/50 hover:text-ocean font-ui text-sm">
              {l.cancel}
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.name} *</label>
              <input value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.slug}</label>
              <input value={editing.slug} onChange={(e) => setEditing({ ...editing, slug: e.target.value })}
                placeholder={l.autoGenerated}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div className="md:col-span-2">
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.sku}</label>
              <div className="flex gap-2">
                <input value={editing.sku || ""} onChange={(e) => setEditing({ ...editing, sku: e.target.value })}
                  placeholder={l.skuHint}
                  className="flex-1 border border-gold/20 px-3 py-2.5 rounded font-ui text-sm font-mono focus:outline-none focus:border-gold" />
                <button type="button" onClick={handleRegenerateSku} disabled={regenSkuLoading}
                  className="px-3 py-2.5 bg-ocean/10 hover:bg-ocean/20 text-ocean rounded font-ui text-xs uppercase tracking-wider transition-colors disabled:opacity-50">
                  {regenSkuLoading ? "…" : l.regenerateSku}
                </button>
              </div>
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.retailPrice} *</label>
              <input type="number" value={editing.price_retail} onChange={(e) => setEditing({ ...editing, price_retail: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.wholesalePrice}</label>
              <input type="number" value={editing.price_wholesale} onChange={(e) => setEditing({ ...editing, price_wholesale: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.category}</label>
              <select value={editing.category} onChange={(e) => setEditing({ ...editing, category: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white">
                {CATEGORIES.map((c) => <option key={c} value={c}>{CATEGORY_LABELS[lang][c]}</option>)}
              </select>
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.stoneType}</label>
              <select value={editing.stone_type} onChange={(e) => setEditing({ ...editing, stone_type: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white">
                {STONE_TYPES.map((s) => <option key={s} value={s}>{STONE_LABELS[lang][s]}</option>)}
              </select>
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.metalType}</label>
              <select value={editing.metal_type} onChange={(e) => setEditing({ ...editing, metal_type: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white">
                {METAL_TYPES.map((m) => <option key={m} value={m}>{METAL_LABELS[lang][m]}</option>)}
              </select>
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.stockStatus}</label>
              <select value={editing.stock_status} onChange={(e) => setEditing({ ...editing, stock_status: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white">
                {STOCK_STATUSES.map((s) => <option key={s} value={s}>{STOCK_LABELS[lang][s]}</option>)}
              </select>
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.stockQty}</label>
              <input type="number" min="0" value={editing.stock_quantity || 0} onChange={(e) => setEditing({ ...editing, stock_quantity: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.weight}</label>
              <input type="number" value={editing.weight_grams} onChange={(e) => setEditing({ ...editing, weight_grams: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.dimensions}</label>
              <input value={editing.dimensions} onChange={(e) => setEditing({ ...editing, dimensions: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.stoneOrigin}</label>
              <input value={editing.stone_origin} onChange={(e) => setEditing({ ...editing, stone_origin: e.target.value })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.sortOrder}</label>
              <input type="number" value={editing.sort_order} onChange={(e) => setEditing({ ...editing, sort_order: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
            <div>
              <label className="block font-ui text-xs text-ocean/60 mb-1 uppercase tracking-wider">{l.minWholesaleQty}</label>
              <input type="number" value={editing.min_wholesale_qty} onChange={(e) => setEditing({ ...editing, min_wholesale_qty: Number(e.target.value) })}
                className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold" />
            </div>
          </div>

          {/* Cost breakdown + live margin */}
          <div className="mt-6 p-4 bg-cream-dark/50 rounded-lg border border-gold/10">
            <h3 className="font-heading text-sm tracking-wider text-ocean mb-3 uppercase">{l.costs}</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {([
                ["material_cost", l.materialCost],
                ["labor_cost", l.laborCost],
                ["packaging_cost", l.packagingCost],
                ["shipping_cost", l.shippingCostField],
              ] as const).map(([key, label]) => (
                <div key={key}>
                  <label className="block font-ui text-[10px] text-ocean/60 mb-1 uppercase tracking-wider">{label}</label>
                  <input type="number" step="0.01" min="0" value={editing[key] || 0}
                    onChange={(e) => setEditing({ ...editing, [key]: Number(e.target.value) })}
                    className="w-full border border-gold/20 px-3 py-2 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
                </div>
              ))}
            </div>
            <div className="mt-4 grid grid-cols-3 gap-3 pt-3 border-t border-gold/10">
              <div>
                <p className="font-ui text-[10px] text-ocean/50 uppercase tracking-wider">{l.totalCost}</p>
                <p className="font-heading text-lg text-ocean mt-0.5">{fmtUSD(editingMargin.cost)}</p>
              </div>
              <div>
                <p className="font-ui text-[10px] text-ocean/50 uppercase tracking-wider">{l.retailPrice}</p>
                <p className="font-heading text-lg text-gold mt-0.5">{fmtUSD(Number(editing.price_retail || 0))}</p>
              </div>
              <div>
                <p className="font-ui text-[10px] text-ocean/50 uppercase tracking-wider">{l.margin}</p>
                <p className={`font-heading text-lg mt-0.5 ${editingMargin.margin >= 50 ? "text-green-700" : editingMargin.margin >= 30 ? "text-yellow-700" : "text-red-600"}`}>
                  {editingMargin.margin.toFixed(1)}%
                </p>
              </div>
            </div>
          </div>

          <div className="mt-6 p-4 bg-cream-dark/50 rounded-lg border border-gold/10">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-heading text-sm tracking-wider text-ocean uppercase">{l.descriptions}</h3>
              <button onClick={handleGenerateDescriptions} disabled={generating}
                className="px-4 py-2 bg-ocean text-cream rounded font-ui text-xs tracking-wider uppercase transition-colors hover:bg-ocean/80 disabled:opacity-50 flex items-center gap-2">
                {generating ? (
                  <>
                    <span className="inline-block w-3 h-3 border-2 border-cream/30 border-t-cream rounded-full animate-spin" />
                    {l.generating}
                  </>
                ) : (
                  l.generateAi + " (EN/ES/DE)"
                )}
              </button>
            </div>

            {/* English */}
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="inline-block px-2 py-0.5 bg-ocean text-cream rounded font-ui text-[10px] uppercase font-bold">EN</span>
                <span className="font-ui text-xs text-ocean/50">English</span>
              </div>
              <div className="space-y-2">
                <input value={editing.short_description} onChange={(e) => setEditing({ ...editing, short_description: e.target.value })}
                  placeholder={l.shortDesc}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
                <textarea value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} rows={3}
                  placeholder={l.fullDesc}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
              </div>
            </div>

            {/* Spanish */}
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="inline-block px-2 py-0.5 bg-ambar text-navy rounded font-ui text-[10px] uppercase font-bold">ES</span>
                <span className="font-ui text-xs text-ocean/50">Espanol</span>
              </div>
              <div className="space-y-2">
                <input value={editing.short_description_es || ""} onChange={(e) => setEditing({ ...editing, short_description_es: e.target.value })}
                  placeholder={lang === "es" ? "Descripcion Corta" : "Short Description (Spanish)"}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
                <textarea value={editing.description_es || ""} onChange={(e) => setEditing({ ...editing, description_es: e.target.value })} rows={3}
                  placeholder={lang === "es" ? "Descripcion Completa" : "Full Description (Spanish)"}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
              </div>
            </div>

            {/* German */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="inline-block px-2 py-0.5 bg-gold text-navy rounded font-ui text-[10px] uppercase font-bold">DE</span>
                <span className="font-ui text-xs text-ocean/50">Deutsch</span>
              </div>
              <div className="space-y-2">
                <input value={editing.short_description_de || ""} onChange={(e) => setEditing({ ...editing, short_description_de: e.target.value })}
                  placeholder={lang === "es" ? "Descripcion Corta (Aleman)" : "Short Description (German)"}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
                <textarea value={editing.description_de || ""} onChange={(e) => setEditing({ ...editing, description_de: e.target.value })} rows={3}
                  placeholder={lang === "es" ? "Descripcion Completa (Aleman)" : "Full Description (German)"}
                  className="w-full border border-gold/20 px-3 py-2.5 rounded font-ui text-sm focus:outline-none focus:border-gold bg-white" />
              </div>
            </div>
          </div>

          {/* Toggles */}
          <div className="flex flex-wrap gap-6 mt-6">
            {[
              { key: "featured", label: l.featured },
              { key: "wholesale_eligible", label: l.wholesaleEligible },
              { key: "new_arrival", label: l.newArrival },
              { key: "visible", label: l.visible },
            ].map(({ key, label }) => (
              <label key={key} className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={!!editing[key]} onChange={(e) => setEditing({ ...editing, [key]: e.target.checked })}
                  className="w-4 h-4 accent-ambar-light" />
                <span className="font-ui text-sm text-ocean">{label}</span>
              </label>
            ))}
          </div>

          {/* Image uploads — redesigned */}
          <div className="mt-6">
            <h3 className="font-heading text-sm tracking-wider text-ocean mb-3 uppercase">{l.images}</h3>

            {/* Drop zone + main preview */}
            <div
              onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
              onDragLeave={() => setDragActive(false)}
              onDrop={(e) => {
                e.preventDefault();
                setDragActive(false);
                if (e.dataTransfer.files?.length) handleFilesSelected(e.dataTransfer.files);
              }}
              className={`relative rounded-lg border-2 border-dashed transition-colors ${dragActive ? "border-ambar bg-ambar/5" : "border-gold/20 bg-cream-dark/30"} p-4`}
            >
              <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                {/* Main preview (big) */}
                <div className="md:col-span-3">
                  <p className="font-ui text-[10px] text-ocean/50 uppercase tracking-wider mb-2">{l.mainPhoto}</p>
                  <div className="aspect-square bg-white rounded-lg border border-gold/20 overflow-hidden flex items-center justify-center relative">
                    {mainImg ? (
                      <>
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={mainImg} alt="" className="w-full h-full object-cover" />
                        <span className="absolute top-2 left-2 bg-ambar text-navy px-2 py-0.5 rounded font-ui text-[10px] uppercase font-bold">
                          ★ {l.mainBadge}
                        </span>
                        <button type="button" onClick={() => clearImage("image_main")}
                          className="absolute top-2 right-2 w-7 h-7 bg-black/60 hover:bg-red-500 text-white rounded-full flex items-center justify-center font-ui text-xs transition-colors">
                          ×
                        </button>
                      </>
                    ) : (
                      <div className="text-center px-4">
                        <p className="font-ui text-sm text-ocean/40 mb-1">No main photo</p>
                        <p className="font-ui text-xs text-ocean/30">{l.dropHere}</p>
                      </div>
                    )}
                  </div>
                </div>

                {/* Thumb column */}
                <div className="md:col-span-2 flex flex-col gap-2">
                  <div className="grid grid-cols-4 md:grid-cols-2 gap-2">
                    {IMAGE_FIELDS.filter((f) => f !== "image_main").map((field) => (
                      <div key={field} className="relative aspect-square bg-white rounded border border-gold/15 overflow-hidden group">
                        {editing[field] ? (
                          <>
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img src={editing[field]} alt="" className="w-full h-full object-cover" />
                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-colors flex flex-col items-center justify-center gap-1 opacity-0 group-hover:opacity-100">
                              <button type="button" onClick={() => setAsMain(field)}
                                className="px-2 py-1 bg-ambar text-navy rounded font-ui text-[10px] uppercase font-bold hover:bg-ambar-light">
                                ★ {l.setAsMain}
                              </button>
                              <button type="button" onClick={() => clearImage(field)}
                                className="px-2 py-1 bg-red-500 text-white rounded font-ui text-[10px] uppercase font-bold hover:bg-red-600">
                                {lang === "es" ? "Eliminar" : "Remove"}
                              </button>
                            </div>
                          </>
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-ocean/20 font-ui text-xs">
                            +
                          </div>
                        )}
                      </div>
                    ))}
                  </div>

                  <button type="button" onClick={openPicker} disabled={!!uploadingField}
                    className="mt-1 w-full py-2.5 bg-ambar-light hover:bg-ambar text-navy rounded font-ui text-xs tracking-wider uppercase font-medium transition-colors disabled:opacity-50">
                    {uploadingField ? l.uploading : `+ ${l.uploadPhotos}`}
                  </button>
                  <p className="text-center font-ui text-[10px] text-ocean/40">{l.dropHere}</p>
                </div>
              </div>
            </div>

            {/* URL inputs (fallback for manual entry) */}
            <details className="mt-3">
              <summary className="font-ui text-xs text-ocean/50 cursor-pointer hover:text-ocean">{l.pasteUrl}</summary>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                {IMAGE_FIELDS.map((field) => (
                  <div key={field}>
                    <label className="block font-ui text-[10px] text-ocean/50 mb-1 uppercase">{field}</label>
                    <input value={editing[field] || ""} onChange={(e) => setEditing({ ...editing, [field]: e.target.value })}
                      placeholder="https://..."
                      className="w-full border border-gold/15 px-2 py-1.5 rounded font-ui text-xs focus:outline-none focus:border-gold" />
                  </div>
                ))}
              </div>
            </details>
          </div>

          {/* Save */}
          <div className="flex gap-3 mt-8">
            <button onClick={handleSave}
              className="flex-1 bg-ambar-light hover:bg-ambar text-navy py-3 rounded font-ui text-sm tracking-wider uppercase font-medium transition-colors">
              {isNew ? l.createProduct : l.saveChanges}
            </button>
            <button onClick={() => { setEditing(null); setIsNew(false); }}
              className="px-8 py-3 border border-gold/30 text-ocean rounded font-ui text-sm tracking-wider uppercase transition-colors hover:bg-gold/10">
              {l.cancel}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // --- Main Dashboard with tabs ---
  const tabs: Array<{ key: Tab; label: string }> = [
    { key: "dashboard", label: l.dashboard },
    { key: "products", label: l.products },
    { key: "inventory", label: l.inventory },
    { key: "orders", label: l.orders },
  ];

  return (
    <div className="min-h-screen bg-cream-dark">
      {/* Header */}
      <div className="bg-navy text-cream px-4 sm:px-8 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <h1 className="font-heading text-lg tracking-[0.1em] text-cream">
            {l.title}
          </h1>
          <div className="flex items-center gap-4">
            <LangToggle />
            <Link href="/" className="font-ui text-xs text-cream/50 hover:text-cream transition-colors">{l.viewSite}</Link>
            <button onClick={handleLogout} className="font-ui text-xs text-cream/50 hover:text-cream transition-colors">
              {l.logout}
            </button>
          </div>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="bg-white border-b border-ocean/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-8 flex gap-0 overflow-x-auto">
          {tabs.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`px-6 py-3 font-ui text-sm tracking-wider transition-colors border-b-2 whitespace-nowrap ${
                activeTab === tab.key
                  ? "border-ambar text-ocean font-medium"
                  : "border-transparent text-ocean/40 hover:text-ocean/70"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {message && (
        <div className="bg-ambar-light/20 text-ocean px-4 py-3 text-center font-ui text-sm">
          {message}
        </div>
      )}

      <div className="max-w-7xl mx-auto px-4 sm:px-8 py-8">
        {activeTab === "dashboard" && <DashboardPanel products={products} lang={lang} />}

        {activeTab === "inventory" && <InventoryManager products={products} lang={lang} />}

        {activeTab === "orders" && <OrdersManager />}

        {activeTab === "products" && (
          <>
            {/* Actions */}
            <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
              <div>
                <h2 className="font-heading text-xl tracking-[0.08em] text-ocean">{l.products}</h2>
                <p className="font-ui text-xs text-ocean/40 mt-1">{products.length} {l.productsInDb}</p>
              </div>
              <div className="flex gap-3">
                {!dbReady && (
                  <button onClick={handleSetupDb}
                    className="px-6 py-2.5 bg-ocean text-cream rounded font-ui text-xs tracking-wider uppercase transition-colors hover:bg-ocean-dark">
                    {l.initDb}
                  </button>
                )}
                <button onClick={() => { setEditing({ ...EMPTY_PRODUCT }); setIsNew(true); }}
                  className="px-6 py-2.5 bg-ambar-light hover:bg-ambar text-navy rounded font-ui text-xs tracking-wider uppercase font-medium transition-colors">
                  {l.addProduct}
                </button>
              </div>
            </div>

            {loading ? (
              <p className="text-center font-ui text-sm text-ocean/40 py-20">{l.loading}</p>
            ) : !dbReady ? (
              <div className="text-center py-20 bg-white rounded-lg border border-gold/10">
                <p className="font-heading text-lg text-ocean mb-3">{l.dbNotConnected}</p>
                <p className="font-ui text-sm text-ocean/50 mb-6 max-w-md mx-auto">
                  {l.dbNotConnectedMsg}
                </p>
                <button onClick={handleSetupDb}
                  className="px-8 py-3 bg-ocean text-cream rounded font-ui text-sm tracking-wider uppercase transition-colors hover:bg-ocean/80">
                  {l.initDb}
                </button>
              </div>
            ) : products.length === 0 ? (
              <div className="text-center py-20 bg-white rounded-lg border border-gold/10">
                <p className="font-heading text-lg text-ocean mb-3">{l.noProducts}</p>
                <p className="font-ui text-sm text-ocean/50 mb-6">{l.noProductsMsg}</p>
              </div>
            ) : (
              <div className="bg-white rounded-lg border border-gold/10 overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead className="bg-cream-dark">
                      <tr>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.image}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.sku}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.name}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.category}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.price}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.stock}</th>
                        <th className="text-left font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.status}</th>
                        <th className="text-right font-ui text-xs text-ocean/50 uppercase tracking-wider px-4 py-3">{l.actions}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {products.map((p) => (
                        <tr key={p.id} className="border-t border-gold/10 hover:bg-cream/50 transition-colors">
                          <td className="px-4 py-3">
                            <div className="w-12 h-12 bg-cream-dark rounded overflow-hidden">
                              {p.image_main ? (
                                // eslint-disable-next-line @next/next/no-img-element
                                <img src={p.image_main} alt="" className="w-full h-full object-cover" />
                              ) : (
                                <div className="w-full h-full flex items-center justify-center text-ocean/15 text-xs font-ui">IMG</div>
                              )}
                            </div>
                          </td>
                          <td className="px-4 py-3 font-mono text-xs text-ocean/70">{p.sku || "—"}</td>
                          <td className="px-4 py-3">
                            <p className="font-body text-sm text-ocean font-medium">{p.name}</p>
                            <p className="font-ui text-xs text-ocean/40">{p.id}</p>
                          </td>
                          <td className="px-4 py-3 font-ui text-xs text-ocean/60">{CATEGORY_LABELS[lang][p.category] || p.category}</td>
                          <td className="px-4 py-3 font-ui text-sm text-gold font-medium">${Number(p.price_retail).toFixed(0)}</td>
                          <td className="px-4 py-3 font-ui text-sm text-ocean">{p.stock_quantity ?? 0}</td>
                          <td className="px-4 py-3">
                            <span className={`inline-block px-2 py-0.5 rounded font-ui text-xs ${
                              p.stock_status === "in-stock" ? "bg-green-100 text-green-700" :
                              p.stock_status === "low-stock" ? "bg-yellow-100 text-yellow-700" :
                              p.stock_status === "sold-out" ? "bg-red-100 text-red-700" :
                              "bg-blue-100 text-blue-700"
                            }`}>
                              {STOCK_LABELS[lang][p.stock_status] || p.stock_status}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-right">
                            <div className="flex gap-2 justify-end">
                              <button onClick={() => { setEditing({ ...p }); setIsNew(false); }}
                                className="px-3 py-1.5 bg-gold/10 hover:bg-gold/20 text-ocean rounded font-ui text-xs transition-colors">
                                {l.edit}
                              </button>
                              <button onClick={() => handleDelete(p.id)}
                                className="px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-600 rounded font-ui text-xs transition-colors">
                                {l.delete}
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
